
###

POST http://localhost:3001/api/game/start
content-type: application/json

{

}

###  giusta

POST http://localhost:3001/api/game/end
content-type: application/json

{
  "gameId": 2,
  "route": [
    { "station_from_id": 1, "station_to_id": 2 },
    { "station_from_id": 2, "station_to_id": 3 },
    { "station_from_id": 3, "station_to_id": 4 }
  ]
}


###  sbagliata

POST http://localhost:3001/api/game/end
content-type: application/json

{
  "gameId": 105,
  "route": [1, 2, 3, 5]
}


###  giusta

POST http://localhost:3001/api/game/end
content-type: application/json

{
  "gameId": 2,
  "route": [
    { "station_from_id": 1, "station_to_id": 2 },
    { "station_from_id": 2, "station_to_id": 3 },
    { "station_from_id": 3, "station_to_id": 4 }
  ]
}

###

GET http://localhost:3001/api/stations
content-type: application/json


###

GET http://localhost:3001/api/rank
content-type: application/json

###

POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "mario.rossi@test.com",
  "password": "password123" 
}

###

POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "giulia.bianchi@test.it",
  "password": "secret2026" 
}


###

POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "l.verdi@test.com",
  "password": "metro_fan" 
}


###

POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "e.ferrari@lastrace.net",
  "password": "speedy99" 
}


###

DELETE http://localhost:3001/api/sessions/current


###

GET http://localhost:3001/api/sessions/current